### ISSUE TITLE
Race condition in lib/Quads.py in some write_data(self) calls

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#141]
The following seems to be causing a race condition while doing heavy queries and writes at the same time:

https://github.com/redhat-performance/quads/blob/master/lib/Quads.py#L140:L142

This was a remnant of the legacy ```quads.py``` QUADS iteration prior to daemon/cli where we didn't have proper ```fnctl``` file locking and checks.

This can manifest itself where attemping to add a new schedule to a host will fail with ```ERROR``` and subsequent tries will succeed.

There appear to be two distinct issues, the lines above and this Gerrit patchset seem to solve the  below errors:

Fixed in: ~~https://review.gerrithub.io/#/c/377819/~~

```
OK
OK
OK
ERROR
ERROR
ERROR
OK
OK
```

There is another traceback caused elsewhere that's not tracked down to follow.

**Comment by sadsfae** [comment]
Here's some common tracebacks (WIP on the above lines being the full culprit)

**(quads-cli error)**
```
Traceback (most recent call last):
  File "./quads-cli", line 455, in <module>
    main(sys.argv[1:])
  File "./quads-cli", line 444, in main
    r = requests.post(url, data, headers=headers, timeout=1200)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**(quads-daemon equivalent)**
```
Exception happened during processing of request from ('127.0.0.1', 37602)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/tmp/quads2nBY/quads/bin/quads-daemon", line 48, in do_POST
    quads.read_data()
  File "/tmp/quads2nBY/quads/lib/Quads.py", line 128, in read_data
    self.quads = QuadsData.QuadsData(self.data)
  File "/tmp/quads2nBY/quads/lib/QuadsData.py", line 26, in __init__
    self.hosts = Hosts.Hosts(data)
  File "/tmp/quads2nBY/quads/lib/Hosts.py", line 26, in __init__
    if 'hosts' not in data:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by sadsfae** [comment]
**(most obscure traceback)**

```
Exception happened during processing of request from ('127.0.0.1', 55546)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/tmp/quads6jLQ/quads/bin/quads-daemon", line 664, in do_POST
    cloud_summary = quads.query_cloud_summary(data['date'][0], False)
  File "/tmp/quads6jLQ/quads/lib/Quads.py", line 882, in query_cloud_summary
    if 'post_config' in clouds[cloud] and len(clouds[cloud]['post_config']) > 0:
KeyError: 'cloud17'
```
