### ISSUE TITLE
rare quads-daemon traceback

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#188]
Very rarely (but now twice over the past year) we see this pop up, restarting the daemon "fixes" it.  I'm not sure what's causing it but it seems load / connection related.

```
Traceback (most recent call last):
  File "/opt/quads/bin/quads-cli", line 504, in <module>
    main(sys.argv[1:])
  File "/opt/quads/bin/quads-cli", line 493, in main
    r = requests.post(url, data, headers=headers, timeout=120)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line
475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line
585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line
453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.',
BadStatusLine("''",))
```

**Comment by sadsfae** [comment]
After some investigation there was nothing wrong with the code nor anything evident in the tcpdumps taken.

This seemed to be system related, we had prior XFS corruption on the hypervisor as well as CPU soft lockup on the VM which was most likely contributing to the timeouts experienced (and subsequent tracebacks).  I am closing this now but we can re-open.
