### ISSUE TITLE
move-hosts and move-hosts with dry run error out

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#214]
Just trying `--move-hosts` or using the `--dry-run` flag to simulate what might happen errors out on most recent codebase.

```
[root@host-04 docker]# quads --move-hosts --dry-run
Traceback (most recent call last):
  File "bin/quads-cli", line 441, in <module>
    main(args)
  File "bin/quads-cli", line 292, in main
    host = result['host']
TypeError: string indices must be integers
```

**Comment by sadsfae** [comment]
This seems to be triggered by letting people define hosts with a `--default-cloud` before that cloud exists and the cloud id gets mangled in the database.

**Comment by sadsfae** [comment]
This is confirmed fixed.
