### ISSUE TITLE
traceback in simple_table_web.py for heatmap visuals

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#217]
Getting this in `quads/tools/simple_table_web.py`

```
Traceback (most recent call last):
  File "quads/tools/simple_table_web.py", line 25, in <module>
    content = generator(None, calendar.mdays[_date.month], _date.month, _date.year, gen_time)
  File "/opt/quads/quads/tools/simple_table_generator.py", line 84, in generator
    for h in sorted(quads.get_hosts()):
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
Tracking with this issue.

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/448464
