### ISSUE TITLE
Regenerate Wiki stack traces

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#237]
We get this currently as of `2019-05-03` as of development snapshot `quads-1.0.999-20190503.noarch`

```
Traceback (most recent call last):
  File "/opt/quads/quads/tools/regenerate_wiki.py", line 44, in <module>
    create_input_assignments.main()
  File "/opt/quads/quads/tools/create_input_assignments.py", line 261, in main
    lines.extend(add_row(host))
  File "/opt/quads/quads/tools/create_input_assignments.py", line 201, in add_row
    _date_end = _date_end.end.strftime("%Y-%m-%d")
AttributeError: 'datetime.datetime' object has no attribute 'end'
```

**Comment by sadsfae** [comment]
This is fixed.
