### ISSUE TITLE
badfish.py needs to utilize equivalent of JID_CLEARALL_FORCE

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#261]
It seems that occasionally Dell systems (thus far r620 but probably others) don't always get their job queues cleared with badfish. These cannot be cleared either via the iDRAC UI.

This causes JID's to pile up and never complete.

```
2019-06-08 12:49:38,875 Clearing job queue for job IDs: ['RID_843181825116', 'RID_843175376755', 'RID_843175362071', 'RID_843201688905', 'RID_843208253120', 'RID_843158310720', 'RID_843158246559', 'RID_843208272388', 'RID_843053267400', 'RID_843188446456', 'RID_843181842184', 'RID_843195047909', 'RID_843188431875', 'RID_843201674287', 'RID_843195032975'].
2019-06-08 12:51:31,438 Job queue not cleared, current job queue contains jobs: ['RID_843181825116', 'RID_843175376755', 'RID_843175362071', 'RID_843201688905', 'RID_843208253120', 'RID_843158310720', 'RID_843158246559', 'RID_843208272388', 'RID_843053267400', 'RID_843188446456', 'RID_843181842184', 'RID_843195047909', 'RID_843188431875', 'RID_843201674287', 'RID_843195032975'].
2019-06-08 12:51:31,438 Could not set boot order via Badfish.
Traceback (most recent call last):
  File "/opt/quads/quads/tools/move_and_rebuild_hosts.py", line 151, in move_and_rebuild
    "../../conf/idrac_interfaces.yml"
  File "/opt/quads/quads/tools/badfish.py", line 306, in change_boot
    self.clear_job_queue()
  File "/opt/quads/quads/tools/badfish.py", line 412, in clear_job_queue
    sys.exit(1)
SystemExit: 1
```

![Screenshot_2019-06-08_14-15-30](https://user-images.githubusercontent.com/3940978/59148070-97516000-89fb-11e9-83b4-cebf4e62b104.png)

See full details here on upstream badfish, it should be backported to the `badfish.py` library.

https://github.com/redhat-performance/badfish/issues/30

**Comment by grafuls** [comment]
I tried before to use JID_CLEARALL_FORCE on badfish but it did't clear the queue neither.
I'll do some research on this one.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/457509

**Comment by sadsfae** [comment]
Re-opening this, it seems that the redfish API method still doesn't always clear the same (or as effective as) `jobqueue delete -i JID_CLEARALL_FORCE`
