### ISSUE TITLE
Traceback / further work needed for --mod-cloud

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#348]
We get the following traceback from trying to use `--mod-cloud --vlan`

```
[root@quads ]# quads --mod-cloud cloud14 --vlan 621
Traceback (most recent call last):
  File "/opt/quads/bin/quads-cli", line 1626, in <module>
    main(args)
  File "/opt/quads/bin/quads-cli", line 518, in main
    cloud.update(**clean_data)
  File "/usr/lib/python3.7/site-packages/mongoengine/document.py", line 577, in update
    return self._qs.filter(**self._object_key).update_one(**kwargs)
  File "/usr/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 585, in update_one
    upsert=upsert, multi=False, write_concern=write_concern, **update)
  File "/usr/lib/python3.7/site-packages/mongoengine/queryset/base.py", line 516, in update
    update = transform.update(queryset._document, **update)
  File "/usr/lib/python3.7/site-packages/mongoengine/queryset/transform.py", line 284, in update
    value = field.prepare_query_value(op, value)
  File "/usr/lib/python3.7/site-packages/mongoengine/fields.py", line 1128, in prepare_query_value
    super(ReferenceField, self).prepare_query_value(op, value)
  File "/usr/lib/python3.7/site-packages/mongoengine/base/fields.py", line 191, in prepare_query_value
    self.validate(value)
  File "/usr/lib/python3.7/site-packages/mongoengine/fields.py", line 1133, in validate
    self.error('A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents')
  File "/usr/lib/python3.7/site-packages/mongoengine/base/fields.py", line 166, in error
    raise ValidationError(message, errors=errors, field_name=field_name)
mongoengine.errors.ValidationError: A ReferenceField only accepts DBRef, LazyReference, ObjectId or documents
```

Additionally we need to add the `--mod-cloud` usage to our docs.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/506075
