### ISSUE TITLE
Add sanitization to tenant-managed foreman params in make_instackenv_json

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#379]
Getting a traceback on `make_instackenv_json` recently on `1.1.5` QUADS.

```
Traceback (most recent call last):
  File "/opt/quads/quads/tools/make_instackenv_json.py", line 114, in <module>
    main()
  File "/opt/quads/quads/tools/make_instackenv_json.py", line 108, in main
    make_env_json("instackenv")
  File "/opt/quads/quads/tools/make_instackenv_json.py", line 60, in make_env_json
    _overcloud_result = strtobool(overcloud["result"])
  File "/usr/lib64/python3.7/distutils/util.py", line 307, in strtobool
    raise ValueError("invalid truth value %r" % (val,))
ValueError: invalid truth value 'edit'
```

https://github.com/redhat-performance/quads/blob/master/quads/tools/make_instackenv_json.py#L60

**Comment by sadsfae** [comment]
It appears a tenants free-form data has triggered a bug.

```
    FQDN:         f08-h14-000-1029u.example.com
Operating system:   
    Architecture:           x86_64
    Operating System:       RHEL 8.2
    Build:                  no
    Medium:                 RHEL Local
    Partition Table:        generic-rhel
    PXE Loader:             PXELinux BIOS
    Custom partition table:
Parameters:         
    overcloud => edit
All parameters:     
    overcloud => edit
```

This seems to come from:

```
# quads-cli --full-summary --detail | grep cloud21
cloud21 (mkaliyXXX): 60 (Shift on Stack CI LTA) - 37
```

We'll employ a sanitization fix so that incorrect data field input won't hork the tool and subsequent `instack` data generated for tenants.

**Comment by sadsfae** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/518509
