### ISSUE TITLE
quads-cli traceback for shrink actions on a cloud

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#426]
From RPM and latest tip of master branch:  https://github.com/redhat-performance/quads/commit/32e701c35e17af18250b9776450c1450a35b3db5
```
# quads-cli --shrink --cloud cloud03 --now
```
```python
Are you sure you want to shrink cloud03 to 2023-02-15 17:07? (y/N): y
not all arguments converted during string formatting
Traceback (most recent call last):
  File "/opt/quads/bin/quads-cli", line 78, in <module>
    exit_code = main(_logger=logger)
  File "/opt/quads/bin/quads-cli", line 70, in main
    cli_args=cli_args,
  File "/opt/quads/quads/cli/cli.py", line 77, in run
    return action_meth()
  File "/opt/quads/quads/cli/cli.py", line 862, in action_shrink
    self.shrink(cloud, time_delta, _date, threshold, weeks)
  File "/opt/quads/quads/cli/cli.py", line 812, in shrink
    % shrinkable.name
TypeError: not all arguments converted during string formatting

```

**Comment by kambiz-aghaiepour** [comment]
I was going to say, I'm not familiar with quasd.  But thanks for clarifying it for me.

**Comment by sadsfae** [comment]
> I was going to say, I'm not familiar with quasd. But thanks for clarifying it for me.

I'm sure there's a place nearby that has an open mic so you can practice and hone comedy before unleashing it on the rest of us here.
