### ISSUE TITLE
Some Tracebacks in simple_table_web with a lot of systems

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#430]
When calculating future projections for a lot of systems with `simple_table_web.py` we get this traceback.

```python
Traceback (most recent call last):
  File "/opt/quads/quads/tools/simple_table_web.py", line 67, in <module>
    main()
  File "/opt/quads/quads/tools/simple_table_web.py", line 27, in main
    None, calendar.mdays[_date.month], _date.month, _date.year, gen_time
  File "/opt/quads/quads/tools/simple_table_generator.py", line 55, in generator
    "emoji": "&#%s;" % emojis[int(chosen_color) - 1],
IndexError: list index out of range
```

**Comment by sadsfae** [comment]
Resolving this, `simple-table-web` has undergone a ton of change and improvement and this is no longer an issue.
