### ISSUE TITLE
[RFE] Add Host Metadata for GPU

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#460]
For QUADS 2.0 / APIv3 we should collect GPU model/type hardware information.  All normal compute servers will likely have an integrated GPU as part of the chipset (typically not used) but `lshw` will capture this.

```json
"children" : [
                    {
                      "id" : "display",
                      "class" : "display",
                      "claimed" : true,
                      "handle" : "PCI:0000:03:00.0",
                      "description" : "VGA compatible controller",
                      "product" : "Integrated Matrox G200eW3 Graphics Controller",
                      "vendor" : "Matrox Electronics Systems Ltd.",
                      "physid" : "0",
                      "businfo" : "pci@0000:03:00.0",
                      "version" : "04",
                      "width" : 32,
                      "clock" : 66000000,
                      "configuration" : {
                        "driver" : "mgag200",
                        "latency" : "0",
                        "maxlatency" : "32",
                        "mingnt" : "16"
                      },
```

We just need to determine the relevant values we should capture, I think at a minimum `product` and `vendor`

```
"product" : "Integrated Matrox G200eW3 Graphics Controller",
"vendor" : "Matrox Electronics Systems Ltd.",
```

**Comment by grafuls** [comment]
For this I would make use of the existing `processors` table on DB and add a field for `type` where options are `CPU` or `GPU` only.
We can get product, vendor and handle from lshw.
We'd have to amend the processors blueprint and dao as well as `lshw2meta.py`

**Comment by sadsfae** [comment]
> For this I would make use of the existing `processors` table on DB and add a field for `type` where options are `CPU` or `GPU` only. We can get product, vendor and handle from lshw. We'd have to amend the processors blueprint and dao as well as `lshw2meta.py`

@grafuls sounds good, I think we should run `lshw` against a system with an actual PCI-E GPU however because the return values may be different and more varied.  We need to work with @QuantumPosix to get access to a GPU-enabled system to see what it looks like since we don't have any.

In particular the amount of memory, CUDA cores perhaps and other things we may want to retain here in the metadata model and I do not think the return from a standard integrated i915 chipset is enough to be sure yet of the available values.

**Comment by sadsfae** [comment]
@grafuls @QuantumPosix `lshw` gives us the following information with the generic `nouveau` driver installed:


```
[root@u37-h39-000-r7525 ~]# lshw -numeric -C display
  *-display                 
       description: 3D controller
       product: TU104GL [Tesla T4] [10DE:1EB8]
       vendor: NVIDIA Corporation [10DE]
       physical id: 0
       bus info: pci@0000:41:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm bus_master cap_list fb
       configuration: depth=32 driver=nouveau latency=0 mode=1024x768 visual=truecolor xres=1024 yres=768
       resources: iomemory:1e00-1dff iomemory:1e10-1e0f irq:731 memory:da000000-daffffff memory:1e0d0000000-1e0dfffffff memory:1e100000000-1e101ffffff memory:db000000-db3fffff memory:1dfd0000000-1e0cfffffff memory:1e0e0000000-1e0ffffffff
```

Note there are **two** displays listed, one is always the internal / integrated GPU which we want to omit.

`description: VGA compatible controller` (we should omit)
`description: 3D controller` (what we want to include)

There is other data we can pull from `torch` library but it requires Nvidia driver to be installed, and Nvidia also ships third-party vendor tools to query more information.  I think it's enough to just go with what `lshw` reports rather than complicate having to install a third-party vendor driver and then utilize and support other tools for pulling in more data which may or may not be useful.

```
(venv) [root@u37-h39-000-r7525 ~]# python3 -c "import torch; print(torch.cuda.get_device_name(0));"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/venv/lib64/python3.6/site-packages/torch/cuda/__init__.py", line 326, in get_device_name
    return get_device_properties(device).name
  File "/root/venv/lib64/python3.6/site-packages/torch/cuda/__init__.py", line 356, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/root/venv/lib64/python3.6/site-packages/torch/cuda/__init__.py", line 214, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```


At this time tenants can just look up the GPU model to get more spec info directly from Nvidia for example and I think these key/value pairs are enough for API and quads-web UI filtering:

```
       product: TU104GL [Tesla T4] [10DE:1EB8]
       vendor: NVIDIA Corporation [10DE]
       physical id: 0
       bus info: pci@0000:41:00.0
       version: a1
```

More than one GPU should be evident from an incrementing `physical id` value

**Comment by grafuls** [comment]
This has been implemented so that it picks up the data from the lshw json output as described below, filtering for `children` where `class == 'display' and configuration['driver'] == 'nouveau'`

```
              "children" : [
                {
                  "id" : "display",
                  "class" : "display",
                  "claimed" : true,
                  "handle" : "PCI:0000:41:00.0",
                  "description" : "3D controller",
                  "product" : "TU104GL [Tesla T4]",
                  "vendor" : "NVIDIA Corporation",
                  "physid" : "0",
                  "businfo" : "pci@0000:41:00.0",
                  "logicalname" : "/dev/fb0",
                  "dev" : "29:0",
                  "version" : "a1",
                  "width" : 64,
                  "clock" : 33000000,
                  "configuration" : {
                    "depth" : "32",
                    "driver" : "nouveau",
                    "latency" : "0",
                    "mode" : "1024x768",
                    "visual" : "truecolor",
                    "xres" : "1024",
                    "yres" : "768"
                  },
```

Patch: https://review.gerrithub.io/c/redhat-performance/quads/+/1208789
