### ISSUE TITLE
[BUG] Issue with QUADS 2.0.0 and Public VLAN Handling

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#486]
We should see our routable public VLAN attach here

```
[root@quads2-stage quads]# quads --mod-cloud --cloud cloud05 --vlan 619 
Cloud modified successfully
[root@quads2-stage quads]# quads --ls-vlan
619: Free
620: Free
```

VSC is also mad trying to make the port changes
```
[root@quads2-stage quads]# python /usr/lib/python3.12/site-packages/quads/tools/verify_switchconf.py --cloud cloud05
INFO - Host: f12-h03-000-1029u.stage.rdu2.scalelab.redhat.com
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/quads/tools/verify_switchconf.py", line 70, in verify
    vlan_member = vlan_member_out[0].split()[2][4:].strip(",")
                  ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/quads/tools/verify_switchconf.py", line 149, in <module>
    verify(args.cloud, args.host, args.change)
  File "/usr/lib/python3.12/site-packages/quads/tools/verify_switchconf.py", line 72, in verify
    if not _cloud_obj.vlan and not last_nic:
           ^^^^^^^^^^^^^^^
AttributeError: 'Cloud' object has no attribute 'vlan
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1196307
