### ISSUE TITLE
[BUG] QUADS 2.0.0 notify stack traces trying to find owner attribute in create_message method

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#492]
There appears to be an issue within the `create_message` method referencing the owner attribute:

**Note that we still receive assignment release notifications though**

```
[root@quads2-stage ~]# quads --notify
=============== Additional Message
Traceback (most recent call last):
  File "/usr/bin/quads", line 33, in <module>
    sys.exit(load_entry_point('quads==2.0', 'console_scripts', 'quads')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/main.py", line 64, in main
    _exit_code = qcli.run(
                 ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/cli.py", line 64, in run
    exit_code = action_meth()
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/cli.py", line 1861, in action_notify
    notify(self.logger)
  File "/usr/lib/python3.12/site-packages/quads/tools/notify.py", line 246, in main
    create_message(
  File "/usr/lib/python3.12/site-packages/quads/tools/notify.py", line 104, in create_message
    real_owner = assignment_obj.owner
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Notification' object has no attribute 'owner'
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1196368
