### ISSUE TITLE
QUADS 2.0.0 additional system message with host delta traceback

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#495]
```
[root@quads2-stage quads]# quads --notify
=============== Initial Message
=============== Additional Message
Traceback (most recent call last):
  File "/usr/bin/quads", line 33, in <module>
    sys.exit(load_entry_point('quads==2.0', 'console_scripts', 'quads')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/main.py", line 64, in main
    _exit_code = qcli.run(
                 ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/cli.py", line 64, in run
    exit_code = action_meth()
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/cli.py", line 1870, in action_notify
    notify(self.logger)
  File "/usr/lib/python3.12/site-packages/quads/tools/notify.py", line 246, in main
    host_list = [schedule.host.name for schedule in diff]
                 ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'host'
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1196437
