### ISSUE TITLE
QUADS 2.0.0 timedate / stacktrace on converting strptime for passing --date to move-hosts

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#497]
We're not able to get valid returns for `quads --move-hosts --dry-run --date "YYYY-MM-DD" like we can in 1.1 series:

**2.0.0**

```
[root@quads2-stage quads]# quads --move-hosts --dry-run --date "2024-06-19 12:02"
Check the flask server logs
```

**1.1.8**
```
(root@quads) - (12:48) - (~)
-=>>quads-cli  --move-hosts --dry-run --date "2024-06-19 12:02"
Nothing to do.
```

Logs:

```
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:   File "/usr/lib/python3.12/site-packages/quads/server/blueprints/moves.py", line 26, in get_moves
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]: _date =  datetime.strptime(_params.get("date"), "%Y-%m-%dT%H:%M")
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:   File "/usr/lib64/python3.12/_strptime.py", line 554, in _strptime_datetime
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:                                     ^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:   File "/usr/lib64/python3.12/_strptime.py", line 336, in _strptime
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]:     raise ValueError("unconverted data remains: %s" %
Jun 19 11:44:49 quads2-stage.example.com gunicorn[136513]: ValueError: unconverted data remains: :00
```

**Comment by sadsfae** [comment]
Similar command with similar stack trace:

```
[root@quads2-stage quads]# quads --move-hosts --dry-run --date "2024-06-19T14:02"
Traceback (most recent call last):
  File "/usr/bin/quads", line 33, in <module>
    sys.exit(load_entry_point('quads==2.0', 'console_scripts', 'quads')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/main.py", line 64, in main
    _exit_code = qcli.run(
                 ^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/cli.py", line 64, in run
    exit_code = action_meth()
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/cli/cli.py", line 1504, in action_movehosts
    date = datetime.strptime(self.cli_args.get("datearg"), "%Y-%m-%d %H:%M").isoformat()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-06-19T14:02' does not match format '%Y-%m-%d %H:%M'
```

**Comment by sadsfae** [comment]
This is resolved in https://github.com/redhat-performance/quads/commit/ab04089e37d4263f1d8e0d84109e6d5595b1477b
