### ISSUE TITLE
[BUG] modify_switch_conf stack trace

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#514]
```
/usr/lib/python3.12/site-packages/quads/tools/modify_switch_conf.py --host host.example.com --nic3 1410
```

```
TypeError: 'Interface' object is not subscriptable
INFO - Host: host.example.com
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/quads/tools/modify_switch_conf.py", line 152, in <module>
    verify(
  File "/usr/lib/python3.12/site-packages/quads/tools/modify_switch_conf.py", line 28, in verify
    interfaces = sorted(_host_obj.interfaces, key=lambda k: k["name"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/quads/tools/modify_switch_conf.py", line 28, in <lambda>
    interfaces = sorted(_host_obj.interfaces, key=lambda k: k["name"])
                                                            ~^^^^^^^^
TypeError: 'Interface' object is not subscriptable
```

**Comment by sadsfae** [comment]
Same command run on QUADS 1.1.8 (without the `--change` option):

```
# /opt/quads/quads/tools/modify_switch_conf.py --host host.example.com --nic3 1410
INFO - Host: host.example.com
WARNING - Interface et-0/0/2:2 not using QinQ_vl1410
WARNING - Interface et-0/0/2:2 appears to be a member of VLAN 1472, should be 1410
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1200343
